## 总结

**正确的顺序**

1. 了解Promise基本使用；
2. 看输入题；【可跳过】
3. 手写Promise；
4. 再看输出题。

**输出题总结**

1. promise `状态改变了才触发 then，将其加到微任务队列`；【08】
2. promise.then() 中【`throw new Error()`】，返回 rejected 状态的 promise；【11，12】；
   - promisie内部将其reject
3. promise`内部状态改变后的代码依然运行`；【13】
4. 若触发了 catch，catch【返回 promise】，没触发则跳过这个 catch，执行下一个 then；【14，15】
5. 同一个 promise 可以有`多个 then(catch)，状态改变时，这几个 then(catch)都会触发`；【17】
   - 手写一次就知道了
6. 【`return new Error()，因为不是 throw`】依然是 resolve 状态；【18】
   - 直接return的话就是`返回了个错误对象，而不是抛出错误`。
7. promise 的 then 返回自身会报错【链式循环】；【19】
   - 同样也是手写时需注意的
8. 【值穿透】：
   - then 和 catch 的期望参数为函数，若参数不为函数，则值穿透；【20】
   - 虽然发生了 值穿透 ，这个 then(catch)还是进了微任务队列；【39】
9. await 若是 `pending 状态，之后都不执行`；【32】
10. await 结合 try 的执行过程；【37】；
11. 只要带async了，`即使函数内部全是同步代码，返回的也是promise`；
12. 若await后表达式的值不是Promise，`则返回该值本身，且该行代码是同步运行的`；
13. `finally`；【14，23】
    - finally`不接收来自resolve或者reject的参数`，因为 finally`压根就不知道到底是resolve还是reject`了【不知道 promise 的最终状态】
    - finally().then()时，`then中回调`获取的是`上一个catch或then的返回值`；
    - finally 中应该做一些【`收尾工作`】
14. Promise.all() Promise.race() Promise.any() Promise.allSettled(不会 reject)；【26，27】
    - 知道各自作用，`并且能手写出来`

## 一、new Promise(func)

func 是同步执行的，所以

1. promise `状态改变了才触发 then，将其加到微任务队列`；【08】
2. promise`内部状态改变后的代码依然运行`；【13】



### **终止链式调用的方法**

返回【pending】状态的promise

promise.then(`return new Promise(()=>{})`)，

## 二、p.then()

1. promise 状态改变了`才触发 then，将其加到微任务队列`；【08】
2. promise.then() 中【`throw new Error()`】，返回 rejected 状态的 promise；【11，12】；
   - promisie内部将其reject
3. 同一个 promise 可以有`多个 then(catch)，状态改变时，这几个 then(catch)都会触发`；【17】
   - 手写一次就知道了
4. 【`return new Error()，因为不是 throw`】依然是 resolve 状态；【18】
   - 直接return的话就是`返回了个错误对象，而不是抛出错误`。
5. promise 的 then 返回自身会报错【链式循环】；【19】
   - 同样也是手写时需注意的

## 三、p.catch()

1. 若触发了 catch，catch【返回 promise】，`没触发则跳过这个catch`，执行下一个 then；【14，15】
   - 虽然跳过了，但是还是进了微任务队列

## 四、async-await

1. await 后函数若是 pending 状态，之后都不执行；【32】
2. await 结合 try 的执行过程；【37】；
3. 只要带async了，`即使函数内部全是同步代码，返回的也是promise`；
4. 若await后表达式的值不是Promise，`则返回该值本身，且该行代码是同步运行的`；



### async / await 总结

1. async / await是promise的语法糖，所以async函数也返回Promise；
2. async内部第一个await【await后表达式是Promise才行，若是同步代码，则依然同步执行】之前的代码都是同步的【跟class很像-constructor和原型上方法都写在class里】；
3. await的promise状态没有变化，还是【pending】，则不再执行await之后代码 -- promise中第六条；
4. await得到的是promise成功【resolve】的结果；
5. await`没法得到【reject】结果`，await会把异常抛出，此时需要在await外 `套try/catch`，通过catch捕获异常【reject的reson】；
6. 若await后表达式的值不是Promise，`则返回该值本身，且该行代码是同步运行的`；

### try / catch

**为什么promise不抛出错误？**

因为promise在内部对错误进行了处理；



**那为什么在内部进行处理？**

因为`promise是异步操作`的，`try catch只能捕获在try内部运行的代码`，碰到`promise就直接将其添加到进微任务队列了`，此时`整个try内部是不报错的`，也就捕获不到错误。

同理，对于setTimeout`加入的宏任务`，也没办法捕获。



#### try/catch的两个目的

1. 对错误逻辑进行兜底处理；
2. 对原生的js错误做出场景化的描述，创建一个包含更具体信息的错误对象【对错误进行场景化的包装】，并将其抛出；

### try catch finally

1. try和catch中的`return语句不会影响`finally中语句执行；
2. 若try、catch和finally`都有return，最后以finally为准`。

## 五、值/错误 穿透

**手写下就知道为啥会发生 【值穿透和错误穿透】了**

1. then 和 catch 的`【期望参数】是函数`;

2. 若参数不是函数，则对 onFulfilled 赋值为【`onFulfilled = (value)=> value`】，发生【值穿透】；

3. 但是就算值穿透了，then 和 catch 还是进了微任务队列；

4. 错误穿透 就相当于 then 的第二个参数不是函数，包装了下，所以发生了错误穿透

## 六、finally

【14，23】

**finally**

1. finally`不接收来自resolve或者reject的参数`，因为 finally`压根就不知道到底是resolve还是reject`了【不知道 promise 的最终状态】
2. finally().then()时，`then中回调`获取的是`上一个catch或then的返回值`；
3. finally 中应该做一些【`收尾工作`】

## 七、all、race、any、allSettle

### all

`全部都 resolve 才 resolve`，此时返回数组【结果与入参一一对应】

`一个 reject 就 reject`，reject的reason就用那个reason

### race

返回`最快有结果的那个`，不管成功还是失败；

### any

`只要有一个成功了，就返回成功的`；

全部失败了，才返回失败的数组；

### allSettle

不管成功失败，都将结果添加到返回的数组中；

成功的，添加 {status:fulfilled,value:value};

失败的，添加 {status:rejected,reason:reason};
